version: '3'

networks:
  intranet:
    driver: bridge

volumes:
  hydra_db:
    driver: local
  keto_db:
    driver: local
  rules:
    driver: local

services:
  hydra_postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: hydra-db
    environment:
      - POSTGRES_USER=${HYDRA_POSTGRES_USER}
      - POSTGRES_PASSWORD=${HYDRA_POSTGRES_PASSWORD}
      - POSTGRES_DB=${HYDRA_POSTGRES_DB}
    volumes:
    - ${DATA_PATH_HOST}/hydra_db:/var/lib/postgresql/data
    networks:
      - intranet

  keto_postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: keto-db
    environment:
      - POSTGRES_USER=${KETO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${KETO_POSTGRES_PASSWORD}
      - POSTGRES_DB=${KETO_POSTGRES_DB}
    volumes:
      - ${DATA_PATH_HOST}/keto_db:/var/lib/postgresql/data
    networks:
      - intranet
    ports:
      - "5432:5432"

  hydra_migrate:
    image: oryd/hydra:${HYDRA_VERSION}
    container_name: hydra-migrate-v1
    depends_on:
      - hydra_postgres
    networks:
    - intranet
    volumes:
      - ./config/hydra-config.yaml:/configuration/hydra-config.yaml
    entrypoint: hydra
    command: "--config /configuration/hydra-config.yaml migrate sql --yes -e"
    tty: false

  keto_migrate:
    image: oryd/keto:${KETO_VERSION}
    container_name: keto-migrate
    depends_on:
      - keto_postgres
    networks:
      - intranet
    volumes:
      - ./config/keto-config.yaml:/configuration/keto-config.yaml
    entrypoint: keto
    command: " --config /configuration/keto-config.yaml migrate sql -e"
    tty: false

  oathkeeper:
    image: oryd/oathkeeper:${OATHKEEPER_VERSION}
    container_name: oathkeeper
    depends_on:
      - keto
    networks:
      - intranet
    volumes:
      - ./config/oathkeeper-config.yaml:/configuration/oathkeeper-config.yaml
      - ./jwks.json:/tokens/jwks.json
      - ./resources/:/resources/
    entrypoint: oathkeeper
    ports:
      - "4456:4456"
      - "4455:4455"
    command: "--config /configuration/oathkeeper-config.yaml serve all"

  keto:
    image: oryd/keto:${KETO_VERSION}
    container_name: keto
    depends_on:
      - keto_migrate
    networks:
      - intranet
    volumes:
      - ./config/keto-config.yaml:/configuration/keto-config.yaml
    ports:
      - "4466:4466"
    entrypoint: keto
    command: "--config /configuration/keto-config.yaml serve all"

  hydra:
    image: oryd/hydra:${HYDRA_VERSION}
    container_name: hydra
    depends_on:
    - hydra_migrate
    volumes:
      - ./config/hydra-config.yaml:/configuration/hydra-config.yaml
    networks:
      - intranet
    ports:
      - "9003:4444"
      - "9001:4445"
    entrypoint: hydra
    command: "--config /configuration/hydra-config.yaml serve all --dangerous-force-http"
