version: '3'

networks:
  hydra:
    driver: bridge

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
    - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    networks:
      - hydra
  #Do migration before starting the server
  hydra-migrate:
    image: oryd/hydra:${HYDRA_VERSION}
    container_name: hydra-migrate-v1
    depends_on:
      - postgres
    environment:
    - DATABASE_URL=${DATABASE_URL}
    networks:
    - hydra
    entrypoint: hydra
    command: "migrate sql $DATABASE_URL"
    tty: false

  hydra:
    image: oryd/hydra:${HYDRA_VERSION}
    container_name: hydra-v1
    hostname: ${HYDRA_HOST}
#    depends_on:
#    - hydra-migrate
    environment:
      - SYSTEM_SECRET=${SYSTEM_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - OAUTH2_ISSUER_URL=${OAUTH2_ISSUER_URL}
      - OAUTH2_CONSENT_URL=${OAUTH2_CONSENT_URL}
      - OAUTH2_LOGIN_URL=${OAUTH2_LOGIN_URL}
    networks:
      - hydra
    ports:
      - "9000:4444"
      - "9001:4445"
    entrypoint: hydra
    command: "serve all --dangerous-force-http"




